Try to build the war in Docker.
This doesn't work yet.  Building the war may have succeeded somewhat, on my Mac
(not in Docker), by using dependencies cached in my local maven repo.  With a
separate maven-repo in the project, I am still getting errors like this:

| Error Resolve error obtaining dependencies:
Failed to read artifact descriptor for org.grails.plugins:hibernate:zip:3.6.10.14
| Error Failed to read artifact descriptor for org.grails.plugins:tomcat:zip:7.0.52.1

Could not transfer artifact org.grails.plugins:tomcat:pom:7.0.52.1
from/to repo1_maven_org_maven2 (https://repo1.maven.org/maven2): peer not authenticated

Could not transfer artifact org.grails.plugins:hibernate:pom:3.6.10.14
from/to repo1_maven_org_maven2 (https://repo1.maven.org/maven2): peer not authenticated
SSLPeerUnverifiedException: peer not authenticated

That is not even on a clean local repo, so the various things I've tried may have
built up dependencies that would not be reproduced now.  Michael has a tight deadline
for updating the config of this project, so no time to get this working now.